language: php
sudo: false
php:
  - 5.6
  - 7.0
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
before_install:
  - composer selfupdate
install:
  - composer install --no-interaction --prefer-source
script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - ./vendor/bin/test-reporter
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/CHANGE_ME
    on_success: always
    on_failure: always
    on_start: never
