language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.6
    - php: hhvm
    - php: nightly
    - php: 7.0
      env: COVERAGE=yes
    - php: 7.1
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true
before_install:
  - if [[ $TRAVIS_PHP_VERSION != hhvm && $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini; fi;
  - composer selfupdate
install:
  - composer install --no-interaction --optimize-autoloader
script:
  - ./bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - ./bin/test-reporter
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/{GENERATED_KEY}
    on_success: always
    on_failure: always
    on_start: never
